# Permalinks
permalink:           pretty

# Setup
title:               João Carabetta
tagline:             "public data & math"
url:                  http://joaocarabetta.github.io
baseurl:              ""
permalink:            /:year/:month/:day/:title/
pagination: 100
highlighter: rouge

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              João Carabetta
  url:               joaocarabetta.github.io
  email:             joao.carabetta@gmail.com

# Custom vars
version:             1.0.0
# github:
#   repo:              https://github.com/v

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-redirect-from


  # Markdown settings
kramdown:
  auto_ids: false
  enable_coderay: false
  entity_output: as_char
  footnote_nr: 1
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6

  # Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
